# -*- coding: utf-8 -*-
"""Home Credit Indonesia-Market Campaign

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-EKJfElo8mOp_tHh1ORRyjPIdbAEA68A

**PERMASALAHAN**

Tim Produk, dibantu oleh Tim Marketing, saat ini sedang meluncurkan dua produk/jasa terbaru, dan salah satunya merupakan jasa yang digunakan untuk menunjang penjualan produk yang sudah ada, produk PINJAMAN DANA MULTIGUNA. Oleh karena itu, mereka sedang membutuhkan Tim Data untuk melakukan beberapa analisa yang sangat mendesak untuk membantu mereka meningkatkan peluang cross-selling produk/jasa terbaru mereka untuk tahap awal (A/B testing). Sayangnya, saat ini tidak ada BI yang tersedia di Business Intelligence Center. Oleh karena itu, seorang Data Scientist di tim CRM Analytics dan anda sebagai Data Scientist Intern akan ditugaskan menyelesaikan permasalahan tersebut. Ini adalah peluang anda untuk menunjukkan kemampuan anda dan juga sebagai jalan untuk anda membiasakan diri dengan apa yang Data Scientist di Home Credit kerjakan.

Mereka ingin mengetahui pada grup umur saat mendaftar yang mana mayoritas pelanggan tersegmentasi jika :

- "Late Ten" : Age<20

- "Twenty" : 20<=Age<30

- "Thirty" : 30<=Age<40

- "Fourty" : 40<=Age<50

- "Fifty" : 50<=Age<60

- "Above_Sixty" : 60<=Age

Sebagai catatan, tim marketing hanya membutuhkan data pelanggan yang tidak memiliki kesulitan pembayaran (karena ini terkait dengan kemampuan mereka dalam membeli produk) dan tinggal di wilayah yang diberi rating 3 (REGION_RATING_CLIENT_W_CITY) serta melakukan transaksi pada tanggal 1 Januari 2017 - 31 Desember 2018.

Data yang dibutuhkan untuk analisis ini akan disediakan oleh Tim Marketing dan dapat diunduh pada bagian Sumber Daya yang Dapat Digunakan.

Tentukan 3 urutan grup usia yang paling dominan!


---

**SOLUSI**
"""

#memanggil data yang diinginkan

import pandas as pd
data=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Marketing_Campaign_Data_A-21492758-f47a-4913-971e-68c9a721311a.csv")
data.head()

data.info()

#mengganti tipe data

import datetime as dt

data['APPL_DATETIME']=pd.to_datetime(data['APPL_DATETIME']).dt.date
data['APPL_DATETIME']

data['DATE_BIRTH']=pd.to_datetime(data['DATE_BIRTH']).dt.date
data['DATE_BIRTH']

#menghitung umur

AGE=data['APPL_DATETIME']-data['DATE_BIRTH']
AGE.head()

#Konversi ke bentuk integer

import numpy as np

AGE_DAYS = (AGE/np.timedelta64(1, 'D')).astype(int)
AGE_DAYS

#menghitung umur dalam Tahun

AGE_YEARS = AGE_DAYS/365
AGE_YEARS

"""Segmentasi grup umur pelanggan akan dikategorikan berdasarkan AGE_YEARS:

"Late Ten" : Age<20

"Twenty" : 20<=Age<30

"Thirty" : 30<=Age<40

"Fourty" : 40<=Age<50

"Fifty" : 50<=Age<60

"Above_Sixty" : 60<=Age
"""

#Membentuk segmentasi grup umur

def age(Ayer):
    if (Ayer<20):
     return "Late Ten"
    if (Ayer >=20 and Ayer < 30):
     return "Twenty"
    if (Ayer >=30 and Ayer < 40):
     return "Thirty"
    if (Ayer >=40 and Ayer < 50):
     return "Fourty"
    if (Ayer >=50 and Ayer < 60):
     return "Fifty"
    if (Ayer >= 60):
     return "Above Sixty"

print([age(AG) for AG in AGE_YEARS])

#menggabungkan variabel ke dalam dataset

data_fiks=data.assign(AGE=AGE_YEARS, AGE_CATEGORY=[age(AG) for AG in AGE_YEARS])
data_fiks.head()

"""Data yang akan digunakan adalah data yang memnuhi kriteria sebagai berikut:
* Data pelanggan yang tidak memiliki kesulitan pembayaran (karena ini terkait 
dengan kemampuan mereka dalam membeli produk) ==> TARGET == 0

* Tinggal di wilayah yang diberi rating 3 (REGION_RATING_CLIENT_W_CITY) ==> REGION_RATING_CLIENT_W_CITY == 3

* Melakukan transaksi pada tanggal 1 Januari 2017 - 31 Desember 2018 ==> APPL_DATETIME pada tanggal 2017-01-01 sampai 2018-12-31
"""

#melakukan filtering data yang dibutuhkan

data_fiks1=data_fiks[(data_fiks["TARGET"] == 0) & 
                    (data_fiks["REGION_RATING_CLIENT_W_CITY"] == 3)]
data_fiks1.head()

import datetime

start=datetime.datetime.strptime('2017-01-01', "%Y-%m-%d").date()
end=datetime.datetime.strptime('2018-12-31', "%Y-%m-%d").date()

data_fiks2=data_fiks1[(data_fiks1['APPL_DATETIME'] >= start) & 
                      (data_fiks1['APPL_DATETIME'] <= end)]
data_fiks2.sort_values('APPL_DATETIME')

"""Setelah data bersih dan sudah sesuai dengan kualifikasi, langkah terakhir adalah menghitung jumlah segmen grup umur yang dominan menggunakan syntax 

```
groupby
```


"""

#menghitung jumlah AGE_CATEGORY

data_fiks2.groupby('AGE_CATEGORY')['AGE_CATEGORY'].count().sort_values(ascending=False)

"""Berdasarkan output tersebut dapat dilihat bahwa jumlah grup umur yang paling dominan adalah Fifty yaitu sejumlah 575 pelanggan, kemudian Above Sixty yaitu sejumlah 495 pelanggan, dan Twenty sejumlah 364 pelanggan."""